import { DesignToken } from "@/types/tokens";

/**
 * Styled Components / Emotion Exporter
 */
export function exportToCSSJSPro(tokens: DesignToken[], dsName: string): string {


  const groupedTokens: Record<string, any> = {};

  tokens.forEach(token => {
    const parts = token.path.split('.');
    let current = groupedTokens;

    parts.forEach((part, index) => {
      if (index === parts.length - 1) {
        current[part] = token.ref ? `var(--${token.ref.replace(/[{}]/g, '').replace(/\./g, '-')})` : token.value;
      } else {
        if (!current[part]) current[part] = {};
        current = current[part];
      }
    });
  });

  return `/**
 * Theme Definition - Generated by DesignForge for ${dsName}
 */
export const theme = ${JSON.stringify(groupedTokens, null, 2)};

export type Theme = typeof theme;
`;
}
