import { DesignToken } from "@/types/tokens";

/**
 * Flutter (Dart) Exporter
 */
export function exportToFlutterPro(tokens: DesignToken[], dsName: string): string {
  const colorTokens = tokens.filter(t => t.type === 'color');
  const spacingTokens = tokens.filter(t => t.type === 'spacing' || t.path.includes('spacing'));

  const hexToFlutterColor = (hex: string) => {
    if (!hex || typeof hex !== 'string') return 'Colors.transparent';
    const cleanHex = hex.replace('#', '');
    return `Color(0xFF${cleanHex.toUpperCase()})`;
  };

  const normalizeKey = (path: string) => {
    return path.replace(/[.-]/g, '_').toLowerCase();
  };

  return `import 'package:flutter/material.dart';

/**
 * design_tokens.dart
 * Generated by DesignForge for ${dsName}
 */
class DesignTokens {
  static const colors = _Colors();
  static const spacing = _Spacing();
}

class _Colors {
  const _Colors();
  ${colorTokens.map(t => {
    const key = normalizeKey(t.path);
    return `final ${key} = ${t.ref ? normalizeKey(t.ref.replace(/[{}]/g, '')) : hexToFlutterColor(t.value as string)};`;
  }).join('\n  ')}
}

class _Spacing {
  const _Spacing();
  ${spacingTokens.map(t => {
    const key = normalizeKey(t.path);
    const val = parseFloat(String(t.value)) || 0;
    return `final ${key} = ${val}.0;`;
  }).join('\n  ')}
}
`;
}
