import { DesignToken } from "@/types/tokens";

/**
 * Jetpack Compose Exporter
 */
export function exportToKotlinPro(tokens: DesignToken[], dsName: string): string {
    const colorTokens = tokens.filter(t => t.type === 'color');
    const spacingTokens = tokens.filter(t => t.type === 'spacing' || t.path.includes('spacing'));
    const radiusTokens = tokens.filter(t => t.type === 'borderRadius' || t.path.includes('radius'));

    const hexToComposeColor = (hex: string) => {
        if (!hex || typeof hex !== 'string') return 'Color.Transparent';
        const cleanHex = hex.replace('#', '');
        return `Color(0xFF${cleanHex.toUpperCase()})`;
    };

    const normalizeKey = (path: string) => {
        return path.replace(/[.-]/g, '_').toLowerCase();
    };

    const dsNameCamel = dsName.replace(/\s+/g, '');

    return `package com.designforge.${dsNameCamel.toLowerCase()}

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily

/**
 * DesignTokens.kt
 * Generated by DesignForge
 */
object ${dsNameCamel}Tokens {
    object Colors {
        ${colorTokens.map(t => {
        const key = normalizeKey(t.path);
        return `val ${key} = ${t.ref ? normalizeKey(t.ref.replace(/[{}]/g, '')) : hexToComposeColor(t.value as string)}`;
    }).join('\n        ')}
    }

    object Spacing {
        ${spacingTokens.map(t => {
        const key = normalizeKey(t.path);
        const val = parseFloat(String(t.value)) || 0;
        return `val ${key} = ${val}.dp`;
    }).join('\n        ')}
    }

    object Radius {
        ${radiusTokens.map(t => {
        const key = normalizeKey(t.path);
        const val = parseFloat(String(t.value)) || 0;
        return `val ${key} = ${val}.dp`;
    }).join('\n        ')}
    }
}
`;
}
