import { GeneratedDesignSystem } from "@/types/designSystem";

export function exportToStaticDocs(ds: GeneratedDesignSystem): string {
    const dsJson = JSON.stringify(ds, null, 2).replace(/</g, '\\u003c'); // Escape script tags in JSON

    const escapeHtml = (str: string) => {
        return String(str)
            .replace(/&/g, "&amp;")
            .replace(/</g, "&lt;")
            .replace(/>/g, "&gt;")
            .replace(/"/g, "&quot;")
            .replace(/'/g, "&#039;");
    };

    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${escapeHtml(ds.name)} | Design System Documentation</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&family=${ds.typography.fontFamily.heading.replace(/ /g, '+')}:wght@400;700&family=${ds.typography.fontFamily.body.replace(/ /g, '+')}:wght@400;500;700&display=swap" rel="stylesheet">
    <style>
        :root {
            --primary: ${ds.colors.primary};
            --on-primary: ${ds.colors.onPrimary};
            --background: ${ds.colors.background};
            --surface: ${ds.colors.surface};
            --text: ${ds.colors.text};
            --text-secondary: ${ds.colors.textSecondary};
            --border: ${ds.colors.border};
        }
        body {
            font-family: '${ds.typography.fontFamily.body}', sans-serif;
            background-color: var(--background);
            color: var(--text);
        }
        h1, h2, h3, h4 {
            font-family: '${ds.typography.fontFamily.heading}', sans-serif;
        }
        .token-card {
            background-color: var(--surface);
            border: 1px solid var(--border);
            border-radius: ${ds.borderRadius.md};
            box-shadow: ${ds.shadows.sm};
            transition: all 0.3s ease;
        }
        .token-card:hover {
            box-shadow: ${ds.shadows.md};
            transform: translateY(-2px);
        }
        .swatch {
            border-radius: ${ds.borderRadius.sm};
            border: 1px solid var(--border);
        }
    </style>
</head>
<body class="min-h-screen">
    <nav class="sticky top-0 z-50 bg-white/80 backdrop-blur-md border-b border-gray-200">
        <div class="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
            <div class="flex items-center gap-3">
                <div class="w-8 h-8 rounded-lg bg-[var(--primary)] shadow-lg shadow-[var(--primary)]/20"></div>
                <span class="font-black text-xl tracking-tighter uppercase">${escapeHtml(ds.name)}</span>
            </div>
            <div class="text-[10px] font-black uppercase tracking-widest text-gray-400">
                Generated by DesignForge AI
            </div>
        </div>
    </nav>

    <main class="max-w-7xl mx-auto px-6 py-12">
        <header class="mb-16">
            <h1 class="text-6xl font-black tracking-tighter mb-4">Design System <br/> Foundation</h1>
            <p class="text-xl text-gray-500 max-w-2xl leading-relaxed">
                A comprehensive guide to the visual language, design tokens, and core principles of the ${escapeHtml(ds.name)}.
            </p>
        </header>

        <!-- Colors Section -->
        <section class="mb-20">
            <div class="flex items-center gap-4 mb-8">
                <h2 class="text-3xl font-bold tracking-tight">Color Palette</h2>
                <div class="h-px flex-1 bg-gray-100"></div>
            </div>
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6" id="color-grid">
                <!-- Colors injected here -->
            </div>
        </section>

        <!-- Typography Section -->
        <section class="mb-20">
            <div class="flex items-center gap-4 mb-8">
                <h2 class="text-3xl font-bold tracking-tight">Typography</h2>
                <div class="h-px flex-1 bg-gray-100"></div>
            </div>
            <div class="token-card p-8 space-y-8" id="typography-display">
                <!-- Typography injected here -->
            </div>
        </section>

        <!-- Spacing & Radius -->
        <div class="grid md:grid-cols-2 gap-12 mb-20">
            <section>
                <div class="flex items-center gap-4 mb-8">
                    <h2 class="text-2xl font-bold tracking-tight">Spacing Scale</h2>
                    <div class="h-px flex-1 bg-gray-100"></div>
                </div>
                <div class="token-card p-6 space-y-3" id="spacing-grid"></div>
            </section>
            <section>
                <div class="flex items-center gap-4 mb-8">
                    <h2 class="text-2xl font-bold tracking-tight">Border Radius</h2>
                    <div class="h-px flex-1 bg-gray-100"></div>
                </div>
                <div class="token-card p-6 space-y-3" id="radius-grid"></div>
            </section>
        </div>

        <footer class="mt-32 pt-12 border-t border-gray-100 flex justify-between items-center opacity-50">
            <p class="text-xs font-medium">&copy; 2026 ${escapeHtml(ds.name)}. All rights reserved.</p>
            <div class="flex gap-6">
                <span class="text-xs uppercase font-black tracking-widest">v1.0.0</span>
            </div>
        </footer>
    </main>

    <script>
        const ds = ${dsJson};
        const escapeHtml = (str) => String(str ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#039;');
        const isValidColor = (c) => typeof c === 'string' && /^(#[0-9a-fA-F]{3,8}|(rgb|hsl)a?\([^)]*\)|var\(--[\w-]+\)|[a-zA-Z]+)$/.test(c.trim());
        const safeColor = (c) => isValidColor(c) ? c : 'transparent';
        const safeLen = (v) => typeof v === 'string' && /^[\d.]+(px|rem|em|%)?$/.test(v.trim()) ? v : '0';

        // Render Colors
        const colorGrid = document.getElementById('color-grid');
        const colorKeys = ['primary', 'secondary', 'accent', 'background', 'surface', 'text', 'success', 'warning', 'error'];
        
        colorKeys.forEach(key => {
            if (!ds.colors[key]) return;
            const card = document.createElement('div');
            card.className = 'token-card p-4 flex flex-col gap-4';
            const swatch = document.createElement('div');
            swatch.className = 'swatch h-24 w-full shadow-inner';
            swatch.style.backgroundColor = safeColor(ds.colors[key]);
            const meta = document.createElement('div');
            const h4 = document.createElement('h4');
            h4.className = 'font-bold text-sm uppercase tracking-wider';
            h4.textContent = key;
            const p = document.createElement('p');
            p.className = 'text-[10px] font-mono text-gray-400';
            p.textContent = String(ds.colors[key] ?? '');
            meta.appendChild(h4); meta.appendChild(p);
            card.appendChild(swatch); card.appendChild(meta);
            colorGrid.appendChild(card);
        });

        // Render Typography
        const typoDisplay = document.getElementById('typography-display');
        const fontSizes = ds.typography.sizes || ds.typography.fontSizes;
        Object.entries(fontSizes).reverse().forEach(([key, size]) => {
            const item = document.createElement('div');
            item.className = 'flex items-baseline justify-between py-4 border-b border-gray-50 last:border-0';
            const left = document.createElement('div');
            left.className = 'flex-1';
            const sample = document.createElement('p');
            sample.style.fontSize = safeLen(size);
            sample.style.lineHeight = '1.2';
            sample.textContent = 'The quick brown fox jumps over the lazy dog';
            left.appendChild(sample);
            const right = document.createElement('div');
            right.className = 'text-right ml-8';
            const lab = document.createElement('p');
            lab.className = 'text-[10px] font-black uppercase tracking-widest text-gray-300 mb-1';
            lab.textContent = key;
            const val = document.createElement('p');
            val.className = 'text-xs font-mono font-bold';
            val.textContent = String(size);
            right.appendChild(lab); right.appendChild(val);
            item.appendChild(left); item.appendChild(right);
            typoDisplay.appendChild(item);
        });

        // Render Spacing
        const spacingGrid = document.getElementById('spacing-grid');
        Object.entries(ds.spacing.scale).slice(0, 8).forEach(([key, val]) => {
            const item = document.createElement('div');
            item.className = 'flex items-center gap-4';
            const k = document.createElement('div'); k.className = 'text-[10px] font-mono w-4'; k.textContent = key;
            const bar = document.createElement('div'); bar.className = 'h-2 bg-[var(--primary)] opacity-40 rounded-full'; bar.style.width = safeLen(val);
            const v = document.createElement('div'); v.className = 'text-[10px] font-mono ml-auto opacity-40'; v.textContent = String(val);
            item.appendChild(k); item.appendChild(bar); item.appendChild(v);
            spacingGrid.appendChild(item);
        });

        // Render Radius
        const radiusGrid = document.getElementById('radius-grid');
        Object.entries(ds.borderRadius).forEach(([key, val]) => {
            const item = document.createElement('div');
            item.className = 'flex items-center gap-4';
            const k = document.createElement('div'); k.className = 'text-[10px] font-mono w-6'; k.textContent = key;
            const box = document.createElement('div'); box.className = 'h-10 w-10 border-2 border-[var(--primary)] border-dashed opacity-50'; box.style.borderRadius = safeLen(val);
            const v = document.createElement('div'); v.className = 'text-[10px] font-mono ml-auto opacity-40'; v.textContent = String(val);
            item.appendChild(k); item.appendChild(box); item.appendChild(v);
            radiusGrid.appendChild(item);
        });
    </script>
</body>
</html>`;
}
