import { GeneratedDesignSystem } from "@/types/designSystem";

export function exportToStaticDocs(ds: GeneratedDesignSystem): string {
    const dsJson = JSON.stringify(ds, null, 2);

    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${ds.name} | Design System Documentation</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&family=${ds.typography.fontFamily.heading.replace(/ /g, '+')}:wght@400;700&family=${ds.typography.fontFamily.body.replace(/ /g, '+')}:wght@400;500;700&display=swap" rel="stylesheet">
    <style>
        :root {
            --primary: ${ds.colors.primary};
            --on-primary: ${ds.colors.onPrimary};
            --background: ${ds.colors.background};
            --surface: ${ds.colors.surface};
            --text: ${ds.colors.text};
            --text-secondary: ${ds.colors.textSecondary};
            --border: ${ds.colors.border};
        }
        body {
            font-family: '${ds.typography.fontFamily.body}', sans-serif;
            background-color: var(--background);
            color: var(--text);
        }
        h1, h2, h3, h4 {
            font-family: '${ds.typography.fontFamily.heading}', sans-serif;
        }
        .token-card {
            background-color: var(--surface);
            border: 1px solid var(--border);
            border-radius: ${ds.borderRadius.md};
            box-shadow: ${ds.shadows.sm};
            transition: all 0.3s ease;
        }
        .token-card:hover {
            box-shadow: ${ds.shadows.md};
            transform: translateY(-2px);
        }
        .swatch {
            border-radius: ${ds.borderRadius.sm};
            border: 1px solid var(--border);
        }
    </style>
</head>
<body class="min-h-screen">
    <nav class="sticky top-0 z-50 bg-white/80 backdrop-blur-md border-b border-gray-200">
        <div class="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
            <div class="flex items-center gap-3">
                <div class="w-8 h-8 rounded-lg bg-[var(--primary)] shadow-lg shadow-[var(--primary)]/20"></div>
                <span class="font-black text-xl tracking-tighter uppercase">${ds.name}</span>
            </div>
            <div class="text-[10px] font-black uppercase tracking-widest text-gray-400">
                Generated by DesignForge AI
            </div>
        </div>
    </nav>

    <main class="max-w-7xl mx-auto px-6 py-12">
        <header class="mb-16">
            <h1 class="text-6xl font-black tracking-tighter mb-4">Design System <br/> Foundation</h1>
            <p class="text-xl text-gray-500 max-w-2xl leading-relaxed">
                A comprehensive guide to the visual language, design tokens, and core principles of the ${ds.name}.
            </p>
        </header>

        <!-- Colors Section -->
        <section class="mb-20">
            <div class="flex items-center gap-4 mb-8">
                <h2 class="text-3xl font-bold tracking-tight">Color Palette</h2>
                <div class="h-px flex-1 bg-gray-100"></div>
            </div>
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6" id="color-grid">
                <!-- Colors injected here -->
            </div>
        </section>

        <!-- Typography Section -->
        <section class="mb-20">
            <div class="flex items-center gap-4 mb-8">
                <h2 class="text-3xl font-bold tracking-tight">Typography</h2>
                <div class="h-px flex-1 bg-gray-100"></div>
            </div>
            <div class="token-card p-8 space-y-8" id="typography-display">
                <!-- Typography injected here -->
            </div>
        </section>

        <!-- Spacing & Radius -->
        <div class="grid md:grid-cols-2 gap-12 mb-20">
            <section>
                <div class="flex items-center gap-4 mb-8">
                    <h2 class="text-2xl font-bold tracking-tight">Spacing Scale</h2>
                    <div class="h-px flex-1 bg-gray-100"></div>
                </div>
                <div class="token-card p-6 space-y-3" id="spacing-grid"></div>
            </section>
            <section>
                <div class="flex items-center gap-4 mb-8">
                    <h2 class="text-2xl font-bold tracking-tight">Border Radius</h2>
                    <div class="h-px flex-1 bg-gray-100"></div>
                </div>
                <div class="token-card p-6 space-y-3" id="radius-grid"></div>
            </section>
        </div>

        <footer class="mt-32 pt-12 border-t border-gray-100 flex justify-between items-center opacity-50">
            <p class="text-xs font-medium">&copy; 2026 ${ds.name}. All rights reserved.</p>
            <div class="flex gap-6">
                <span class="text-xs uppercase font-black tracking-widest">v1.0.0</span>
            </div>
        </footer>
    </main>

    <script>
        const ds = ${dsJson};

        // Render Colors
        const colorGrid = document.getElementById('color-grid');
        const colorKeys = ['primary', 'secondary', 'accent', 'background', 'surface', 'text', 'success', 'warning', 'error'];
        
        colorKeys.forEach(key => {
            if (!ds.colors[key]) return;
            const card = document.createElement('div');
            card.className = 'token-card p-4 flex flex-col gap-4';
            card.innerHTML = \`
                <div class="swatch h-24 w-full shadow-inner" style="background-color: \${ds.colors[key]}"></div>
                <div>
                    <h4 class="font-bold text-sm uppercase tracking-wider">\${key}</h4>
                    <p class="text-[10px] font-mono text-gray-400">\${ds.colors[key]}</p>
                </div>
            \`;
            colorGrid.appendChild(card);
        });

        // Render Typography
        const typoDisplay = document.getElementById('typography-display');
        const fontSizes = ds.typography.sizes || ds.typography.fontSizes;
        Object.entries(fontSizes).reverse().forEach(([key, size]) => {
            const item = document.createElement('div');
            item.className = 'flex items-baseline justify-between py-4 border-b border-gray-50 last:border-0';
            item.innerHTML = \`
                <div class="flex-1">
                    <p style="font-size: \${size}; line-height: 1.2; font-weight: \${ds.typography.weights.bold}">The quick brown fox jumps over the lazy dog</p>
                </div>
                <div class="text-right ml-8">
                    <p class="text-[10px] font-black uppercase tracking-widest text-gray-300 mb-1">\${key}</p>
                    <p class="text-xs font-mono font-bold">\${size}</p>
                </div>
            \`;
            typoDisplay.appendChild(item);
        });

        // Render Spacing
        const spacingGrid = document.getElementById('spacing-grid');
        Object.entries(ds.spacing.scale).slice(0, 8).forEach(([key, val]) => {
            const item = document.createElement('div');
            item.className = 'flex items-center gap-4';
            item.innerHTML = \`
                <div class="text-[10px] font-mono w-4">\${key}</div>
                <div class="h-2 bg-[var(--primary)] opacity-40 rounded-full" style="width: \${val}"></div>
                <div class="text-[10px] font-mono ml-auto opacity-40">\${val}</div>
            \`;
            spacingGrid.appendChild(item);
        });

        // Render Radius
        const radiusGrid = document.getElementById('radius-grid');
        Object.entries(ds.borderRadius).forEach(([key, val]) => {
            const item = document.createElement('div');
            item.className = 'flex items-center gap-4';
            item.innerHTML = \`
                <div class="text-[10px] font-mono w-6">\${key}</div>
                <div class="h-10 w-10 border-2 border-[var(--primary)] border-dashed opacity-50" style="border-radius: \${val}"></div>
                <div class="text-[10px] font-mono ml-auto opacity-40">\${val}</div>
            \`;
            radiusGrid.appendChild(item);
        });
    </script>
</body>
</html>`;
}
