import { GeneratedDesignSystem } from "@/types/designSystem";

export function exportToStorybookAdvanced(ds: GeneratedDesignSystem): string {
    return `/**
 * Advanced Storybook Theme Configuration
 * Generated by DesignForge for: ${ds.name}
 */

import { create } from '@storybook/theming/create';

export const storybookTheme = create({
  base: 'light',
  brandTitle: '${ds.name} Design System',
  brandUrl: 'https://designforge.ai',
  brandImage: 'https://designforge.ai/logo.png',
  brandTarget: '_self',

  // UI
  appBg: '${ds.colors.background}',
  appContentBg: '${ds.colors.surface}',
  appPreviewBg: '${ds.colors.surface}',
  appBorderColor: '${ds.colors.border}',
  appBorderRadius: ${parseInt(ds.borderRadius.md) || 4},

  // Colors
  colorPrimary: '${ds.colors.primary}',
  colorSecondary: '${ds.colors.secondary}',

  // Typography
  fontBase: '"${ds.typography.fontFamily.body}", sans-serif',
  fontCode: '"${ds.typography.fontFamily.mono}", monospace',

  // Text colors
  textColor: '${ds.colors.text}',
  textInverseColor: '${ds.colors.onPrimary}',

  // Toolbar default and active colors
  barTextColor: '${ds.colors.textSecondary}',
  barSelectedColor: '${ds.colors.primary}',
  barBg: '${ds.colors.surface}',

  // Form colors
  inputBg: '${ds.colors.surface}',
  inputBorder: '${ds.colors.border}',
  inputTextColor: '${ds.colors.text}',
  inputBorderRadius: ${parseInt(ds.borderRadius.sm) || 2},
});

/* preview.js content below */
/*
export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
  docs: {
    theme: storybookTheme,
  },
};
*/
`;
}
