import { GeneratedDesignSystem } from "@/types/designSystem";

export function exportToSwiftUI(ds: GeneratedDesignSystem): string {
    const parseToSwiftColor = (hex: string) => {
        // Basic hex parsing for SwiftUI
        const r = parseInt(hex.substring(1, 3), 16) / 255;
        const g = parseInt(hex.substring(3, 5), 16) / 255;
        const b = parseInt(hex.substring(5, 7), 16) / 255;
        return `Color(red: ${r.toFixed(3)}, green: ${g.toFixed(3)}, blue: ${b.toFixed(3)})`;
    };

    return `import SwiftUI

// Design System Guide - Generated by DesignForge
public struct DesignTokens {
    public struct Colors {
        public static let primary = ${parseToSwiftColor(ds.colors.primary)}
        public static let secondary = ${parseToSwiftColor(ds.colors.secondary)}
        public static let accent = ${parseToSwiftColor(ds.colors.accent)}
        public static let background = ${parseToSwiftColor(ds.colors.background)}
        public static let surface = ${parseToSwiftColor(ds.colors.surface)}
        
        public static let success = ${parseToSwiftColor(ds.colors.success)}
        public static let warning = ${parseToSwiftColor(ds.colors.warning)}
        public static let error = ${parseToSwiftColor(ds.colors.error)}
    }
    
    public struct Spacing {
        public static let unit: CGFloat = ${ds.spacing.unit}
        ${Object.entries(ds.spacing.scale).map(([key, val]) => `public static let ${key}: CGFloat = ${parseFloat(val as string)}`).join("\n        ")}
    }
    
    public struct Radius {
        ${Object.entries(ds.borderRadius).map(([key, val]) => `public static let ${key}: CGFloat = ${parseFloat(val)}`).join("\n        ")}
    }
    
    public struct Typography {
        public static func heading(size: CGFloat) -> Font {
            return Font.custom("${ds.typography.fontFamily.heading}", size: size)
        }
        
        public static func body(size: CGFloat) -> Font {
            return Font.custom("${ds.typography.fontFamily.body}", size: size)
        }
    }
}
`;
}
