import { GeneratedDesignSystem } from "@/types/designSystem";

export interface VersionInfo {
  /** Human-readable version label, e.g. "Manual snapshot v3" */
  versionName?: string;
  /** Numeric version, when available */
  versionNumber?: number;
  /** ISO timestamp of when the version was created */
  versionCreatedAt?: string;
}

/**
 * Builds a flat, serializer-friendly payload of the user's design tokens.
 * Used for both JSON and YAML downloads. Strips internal/computed fields.
 *
 * Optional `versionInfo` is included in the payload header so consumers
 * (and downloaded files) record exactly which version they came from.
 */
export function buildTokensPayload(ds: GeneratedDesignSystem, versionInfo?: VersionInfo) {
  const flatColors = Object.fromEntries(
    Object.entries(ds.colors).filter(([, v]) => typeof v === "string")
  ) as Record<string, string>;

  return {
    name: ds.name,
    description: ds.description ?? "",
    generatedAt: new Date().toISOString(),
    version: versionInfo
      ? {
          name: versionInfo.versionName ?? null,
          number: versionInfo.versionNumber ?? null,
          createdAt: versionInfo.versionCreatedAt ?? null,
        }
      : undefined,
    colors: flatColors,
    typography: {
      fontFamily: ds.typography.fontFamily,
      sizes: ds.typography.sizes,
      weights: ds.typography.weights,
      lineHeights: ds.typography.lineHeights,
    },
    spacing: {
      unit: ds.spacing.unit,
      scale: ds.spacing.scale,
    },
    shadows: ds.shadows,
    borderRadius: ds.borderRadius,
    grid: ds.grid,
  };
}

export type TokensPayload = ReturnType<typeof buildTokensPayload>;

/** Tiny YAML serializer for the flat token payload (no external dep). */
export function tokensToYaml(payload: TokensPayload): string {
  const lines: string[] = [];

  const isPlainObject = (v: unknown): v is Record<string, unknown> =>
    typeof v === "object" && v !== null && !Array.isArray(v);

  const formatScalar = (v: unknown): string => {
    if (v === null || v === undefined) return "null";
    if (typeof v === "number" || typeof v === "boolean") return String(v);
    const s = String(v);
    // Quote if contains special chars or leading/trailing space
    if (/[:#\-?{}\[\],&*!|>'"%@`\n]|^\s|\s$/.test(s) || s === "") {
      return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
    }
    return s;
  };

  const walk = (value: unknown, indent: number) => {
    const pad = "  ".repeat(indent);
    if (isPlainObject(value)) {
      for (const [k, v] of Object.entries(value)) {
        if (isPlainObject(v) || Array.isArray(v)) {
          lines.push(`${pad}${k}:`);
          walk(v, indent + 1);
        } else {
          lines.push(`${pad}${k}: ${formatScalar(v)}`);
        }
      }
    } else if (Array.isArray(value)) {
      for (const item of value) {
        if (isPlainObject(item) || Array.isArray(item)) {
          lines.push(`${pad}-`);
          walk(item, indent + 1);
        } else {
          lines.push(`${pad}- ${formatScalar(item)}`);
        }
      }
    } else {
      lines.push(`${pad}${formatScalar(value)}`);
    }
  };

  lines.push("# Design tokens generated by DesignForge");
  walk(payload, 0);
  return lines.join("\n") + "\n";
}
